### ISSUE TITLE
Unable to locate package tvb-....

### ISSUE THREAD

**Issue by RomanKovalev** [umarbrowser/Neuropackage#1]
root@debian:/home/rvk/hw# ls
build      tvb                                      tvb-neurodebian_0.0.1-1_amd64.changes  tvb-neurodebian_0.0.1.orig.tar.gz
dist       tvb-neurodebian-0.0.1                    tvb-neurodebian_0.0.1-1_amd64.deb      tvb-neurodebian-0.0.1.tar.gz
files.txt  tvb-neurodebian_0.0.1-1_amd64.build      tvb-neurodebian_0.0.1-1.debian.tar.xz  tvb_neurodebian.egg-info
setup.py   tvb-neurodebian_0.0.1-1_amd64.buildinfo  tvb-neurodebian_0.0.1-1.dsc            tvb-neurodebian.py
root@debian:/home/rvk/hw# apt-get install tvb-neurodebian_0.0.1-1_amd64.deb 
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package tvb-neurodebian_0.0.1-1_amd64.deb
E: Couldn't find any package by glob 'tvb-neurodebian_0.0.1-1_amd64.deb'
E: Couldn't find any package by regex 'tvb-neurodebian_0.0.1-1_amd64.deb'
root@debian:/home/rvk/hw#

**Comment by umarbrowser** [comment]
You can install it using
1 sudo dpkg -i tvb-neurodebian_0.0.1-1_amd64.deb
2-sudo apt-get install -f tvb-neurodebian_0.0.1-1_amd64.deb
3- sudo gdebi tvb-neurodebian_0.0.1-1_amd64.deb
